### ISSUE TITLE
statement`

### ISSUE THREAD

**Issue by romanlex** [codemodsquad/jscodeshift-add-imports#11]
What is it statement` in example?

**Comment by stolinski** [comment]
I'm also wondering this. Did you find out?

**Comment by bennyxguo** [comment]
@stolinski Couldn't get this package to work, but this one works at stackoverflow: https://stackoverflow.com/questions/46021203/how-to-use-jscodeshift-to-insert-a-line-in-the-beginning-of-the-file

**Comment by jedwards1211** [comment]
Oops sorry I missed this.  It is `j.template.statement`, where `j` is the jscodeshift instance.  I'll update the example
