### ISSUE TITLE
`addImports` produces invalid imports for TypeScript type-only imports

### ISSUE THREAD

**Issue by biowaffeln** [codemodsquad/jscodeshift-add-imports#23]
Here's an example of the issue. The following code

```js
const j = require("jscodeshift").withParser("ts");
const addImports = require("jscodeshift-add-imports");

const code = `
import value from "library"
`;

const { statement } = j.template;

const root = j(code);
addImports(root, [
  statement`import type { Type } from "library"`
]);

console.log(root.toSource());
```

produces an output that looks like this, which is not syntactically valid, at least not in TypeScript (maybe it is in Flow? I'm not entirely sure):
```ts
import value, { type Type } from "library";
```

the expected output should look like this:
```ts
import value from "library";
import type { Type } from "library";
```

**Comment by jedwards1211** [comment]
Ah yes it's valid in Flow.  I guess I'll have to make what you expected the default and an option to turn on the current syntax.  I wish there were a surefire indication in the AST whether it's TS or not but I don't think there is.

**Comment by jedwards1211** [comment]
It's a shame they didn't just support the same syntaxes as babel does...
