### ISSUE TITLE
`addImports` ignores side effect-only imports

### ISSUE THREAD

**Issue by biowaffeln** [codemodsquad/jscodeshift-add-imports#24]
Hey, thanks for the very quick response for the other issue and for the project in general, it's incredibly helpful!
That being said, I stumbled across another issue when importing [side effect-only modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only).
The following code produces an empty string:
```js
const root = j("");
addImports(root, [ statement`import "my-module"`]);
console.log(root.toSource());
```
while the expected behaviour should be that it adds the import statement:

```js
import "my-module"
```

**Comment by jedwards1211** [comment]
Okay, no worries, this is another valid issue 👍  I'll figure it out
