### ISSUE TITLE
Cannot read property 'name' of null when trying to add an import

### ISSUE THREAD

**Issue by danielo515** [codemodsquad/jscodeshift-add-imports#32]
Hello.

Thanks for your contributions to the codemod community.
I'm trying this library on an already existing codemod and, with the most basic example I'm getting this error:

```
    TypeError: Cannot read property 'name' of null

      77 |     });
      78 |     if (shouldAddHookImport)
    > 79 |         addImports(root, statement`import { ${hookName}} from '${importFrom}'`);
         |         ^
      80 |     return root.toSource();
      81 | };
      82 |

      at node_modules/jscodeshift-find-imports/index.js:165:41
          at Array.forEach (<anonymous>)
      at findImports (node_modules/jscodeshift-find-imports/index.js:156:26)
      at node_modules/jscodeshift-find-imports/index.js:30:52
          at Array.forEach (<anonymous>)
      at findImports (node_modules/jscodeshift-find-imports/index.js:30:15)
      at addImports (node_modules/jscodeshift-add-imports/index.js:12:17)
      at transformer (src/mods/replace-HOC-with-hook.ts:79:9)
      at applyTransform (node_modules/jscodeshift/dist/testUtils.js:26:18)
      at runInlineTest (node_modules/jscodeshift/dist/testUtils.js:47:18)
```

The code is a simple js file with a react component, and a bunch of imports:

```
import polyglotProvider from 'components/polyglotProvider';

import Logo from 'icons/Logo.svg';
import React from 'react';

function AccountantHeader({ __, managingCompanyName }) {
    return (
        <div className={styles.background}>
            <div className={styles.container}>
                {managingCompanyName ? (
                    <div>
                        <div className={styles.managingLabel}>
                            {__('managing')}
                        </div>
                        <div className={styles.managingCompany}>
                            {managingCompanyName}
                        </div>
                    </div>
                ) : (
                    <a href="/" className={styles.logoLink}>
                        <Logo className={styles.logoImage} />
                    </a>
                )}
            </div>
        </div>
    );
}

export default polyglotProvider(phrases)(AccountantHeader);
```

**Comment by danielo515** [comment]
Ok, found my mistake.

Seems that you can not use the `template.statement` function with interpolated strings. I leads to empty and weird values.

I just used this instead:

```
const buildImport = (j, identifier, libraryName) =>
    j.importDeclaration(
        [j.importSpecifier(j.identifier(identifier), j.identifier(identifier))],
        j.stringLiteral(libraryName)
    );
```

And works like a charm.
Thanks for this.

**Comment by jedwards1211** [comment]
It's a bit confusing but you can manually call the tagged template literal function, passing an ordinary template literal in the template strings array, to interpolate strings:
```
template.statement([`import { ${hookName} } from '${importFrom}'`])
```
But when using the array brackets like this you can't interpolate AST nodes.

I need to look at the code for the templates and refresh my memory on how it works.  It would be nice if there's a way to make it support interpolating both strings and AST nodes.

**Comment by danielo515** [comment]
Hey, thanks for your answer

> But when using the array brackets like this you can't interpolate AST nodes.

What do you mean? That with regular string interpolation I can put actual nodes instead of strings? Like this?

```
template.statement`import { ${j.identifier('foo')} } from '${j.identifier('bar')}'`
```

> I need to look at the code for the templates and refresh my memory on how it works. It would be nice if there's a way to make it support interpolating both strings and AST nodes.

It will be awesome if that would be possible by just reading jscodeshift docs. But I guess it is just a secondary project of those at FB

**Comment by jedwards1211** [comment]
Basically yeah, except that you would need to do
```
statement`import { ${j.identifier('foo')} } from ${j.stringLiteral('bar')}`
```
except that the string literal part doesn't work for technical reasons...

I think because it's a multi-step process where 1) it puts placeholders in the interpolation positions like

```
import $0 from $1
```
and then 2) tries to parse it and 3) replace the AST nodes for `$0` and `$1` with the nodes you passed.

But because the `$1` isn't syntactically valid in that position it fails:
```
> j.template.statement`import { ${j.identifier('foo')} } from ${j.stringLiteral('bar')}`
Uncaught [SyntaxError: Unexpected token (1:31)
] {
  loc: Position { line: 1, column: 31 },
  pos: 31
}
```

But just the import specifier works:

```js
> j.template.statement`import { ${j.identifier('foo')} } from 'bar'`
Node {
  type: 'ImportDeclaration',
  start: 0,
  end: 36,
  ...
```

Yeah I've gradually learned about jscodeshift features from seeing them used in other transforms, as well as reading its code.
